export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) return res.status(500).json({ error: 'OPENAI_API_KEY is not configured on the server.' });
  try {
    const body = req.body || {};
    const { image, images = [], avatarImage, roomImage, style, scene, setting = 'Default', clothing = 'Keep current', accessories = 'None', sceneTreatment = 'Cinematic', zoom = 'Wide', mode = 'preview', personCount, adjustments = '' } = body;
    const sourceImages = Array.isArray(images) && images.length ? images.filter(Boolean).slice(0, 5) : (image ? [image] : []);
    const styles = {'Anime':'cinematic Japanese anime illustration, polished feature-film quality, expressive faces, detailed hair and eyes, sophisticated cel shading','Fairytale Animation':'premium modern fairytale animated-film illustration, richly detailed painterly characters, expressive faces, soft cinematic lighting','3D Cartoon':'high-end 3D animated feature-film character render, realistic materials, detailed hair and clothing, expressive natural faces, cinematic lighting','Comic Book':'premium graphic-novel illustration, believable anatomy, detailed ink linework, controlled comic shading, rich painted colour','Chibi':'premium chibi character illustration, cute proportions, large expressive eyes, detailed hair and clothing, polished digital painting','Watercolour':'high-end editorial watercolour portrait, recognisable realistic features, delicate layered washes, paper texture, fine brush detail','Pencil Illustration':'highly detailed graphite pencil illustration, realistic facial structure, individual hair strokes, fine shading and paper texture','Pop Art':'premium contemporary pop-art portrait, recognisable face and anatomy, bold graphic colour blocking, crisp halftone texture'};
    const fixedScenes={'Grand Banquet':['standing at the head of the banquet table','seated on the left side of the table','seated on the right side of the table','seated further along the table','standing beside the table'],'Christmas Morning':['kneeling beside the tree with a present','sitting on the floor opening a present','sitting near the presents','standing beside the tree','standing near the fireplace'],'Football Stadium':['standing pitch-side','sitting in the front row','standing beside the advertising boards','walking down the stadium steps','standing near the tunnel entrance'],'Tropical Holiday':['standing beside the shoreline','sitting on a beach lounger','walking near the water','sitting beneath a parasol','standing near tropical plants'],'Enchanted Castle':['standing on the grand staircase','standing beside a window','standing beside a castle table','standing near the fireplace','standing in the hall'],'Birthday Party':['standing beside the birthday cake','sitting near the presents','sitting at the party table','standing beside the decorations','standing near the party table'],'Camping Adventure':['standing beside the tent','sitting beside the campfire','sitting on a camping chair','walking beside the campsite','standing beside the picnic table'],'Ski Holiday':['standing on the snowy slope','sitting at the ski lodge','walking near the lift','standing beside the ski hut','standing beside the piste']};
    const sceneAliases={'Banquet':'Grand Banquet','Christmas':'Christmas Morning','Football':'Football Stadium','Beach':'Tropical Holiday','Birthday':'Birthday Party','Ski Resort':'Ski Holiday','Medieval Castle':'Enchanted Castle'};
    const canonicalScene=sceneAliases[scene]||scene;
    const parseImage=dataUrl=>{const [meta,encoded]=String(dataUrl||'').split(',',2);const m=meta.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64$/);if(!m||!encoded)throw new Error('Invalid image data.');return{buffer:Buffer.from(encoded,'base64'),mime:m[1]};};
    const textFromResponse=data=>typeof data?.output_text==='string'?data.output_text:(data?.output||[]).flatMap(x=>x?.content||[]).filter(x=>typeof x?.text==='string').map(x=>x.text).join('\n');
    if(mode==='analyse'){
      if(!sourceImages.length)return res.status(400).json({error:'Please provide at least one photo.'});
      const content=[{type:'input_text',text:'Analyse ALL supplied customer photos together. Identify the UNIQUE people across the whole set; if the same person appears in more than one photo, count them only once. Count real pets separately. Do not invent anyone. Return ONLY JSON: {"people":number,"pets":number,"notes":"brief neutral description"}. Count children and adults.'},...sourceImages.map(source=>({type:'input_image',image_url:source}))];
      const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.6-luna',input:[{role:'user',content}],max_output_tokens:300})});
      const data=await response.json();if(!response.ok)return res.status(response.status).json({error:data?.error?.message||'Photo analysis failed.'});
      let parsed;try{parsed=JSON.parse(textFromResponse(data).replace(/```json|```/g,'').trim())}catch{parsed={people:1,pets:0,notes:'Please confirm the detected people count.'};}
      const detected=Math.max(1,Math.min(5,Number(parsed.people)||1));return res.status(200).json({people:detected,pets:Math.max(0,Number(parsed.pets)||0),notes:String(parsed.notes||'')});
    }
    if(mode==='styleExamples'){
      const prompt=`Create one high-quality contact sheet of eight separate family character portrait examples with no user interface, no text, no labels, no logos and no borders. Use the same fictional adult couple and two children in every panel so the styles are directly comparable. Exactly 4 columns by 2 rows. Top row: 3D Cartoon, Anime, Fairytale Animation, Comic Book. Bottom row: Chibi, Watercolour, Pencil Illustration, Pop Art. Chest-up family portraits. Each panel must strongly demonstrate its named visual style, with polished commercial quality and clear visual differences. Clean attractive backgrounds, expressive faces, detailed hair and clothing.`;
      const response=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-image-2',prompt,size:'1536x1024',quality:'low',output_format:'png'})});
      const data=await response.json();if(!response.ok)return res.status(response.status).json({error:data?.error?.message||'Style examples could not be generated.'});const result=data?.data?.[0];if(!result?.b64_json)return res.status(502).json({error:'The image service returned no style examples.'});return res.status(200).json({image:`data:image/png;base64,${result.b64_json}`,mode});
    }
    if(!sourceImages.length||!style)return res.status(400).json({error:'Please provide at least one photo and a style.'});
    const count=Math.max(1,Math.min(5,Number(personCount)||1));
    if(mode==='avatars'){
      const prompt=`Create a clean approval sheet of exactly ${count} distinct personalised character avatars from ALL supplied customer photos. Visual style: ${styles[style]||style}. Each supplied photo is identity reference only, not composition. Combine distinct people across the photos into one coherent set; if a source photo contains multiple people, preserve each as a separate person. Preserve each person's face, hair, skin tone, approximate age, body proportions, glasses and distinctive features. Keep identities separate and in source-upload order as practical. Use consistent chest-up or waist-up portraits on a simple neutral background. ${adjustments?`Customer instruction: ${adjustments}`:''} Do not invent people or animals. No text, logos or watermarks.`;
      const form=new FormData();form.append('model','gpt-image-2');sourceImages.forEach((src,i)=>{const a=parseImage(src);form.append('image[]',new Blob([a.buffer],{type:a.mime}),`source-${i+1}.jpg`);});form.append('prompt',prompt);form.append('size','1024x1024');form.append('quality','low');form.append('output_format','png');
      const response=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`},body:form});const data=await response.json();if(!response.ok)return res.status(response.status).json({error:data?.error?.message||'Avatar generation failed.'});const result=data?.data?.[0];if(!result?.b64_json)return res.status(502).json({error:'The image service returned no avatar sheet.'});return res.status(200).json({image:`data:image/png;base64,${result.b64_json}`,people:count,mode});
    }
    if(mode==='room'){
      if(!roomImage)return res.status(400).json({error:'Please provide a room image.'});const artwork=parseImage(image),room=parseImage(roomImage),form=new FormData();form.append('model','gpt-image-2');form.append('image[]',new Blob([artwork.buffer],{type:artwork.mime}),'artwork.png');form.append('image[]',new Blob([room.buffer],{type:room.mime}),'room.jpg');form.append('prompt','Use the supplied room photo as the exact environment. Place the supplied finished artwork as a printed picture inside a simple standard black frame on an appropriate visible wall. Keep the room, furniture, architecture, lighting and perspective realistic. Do not alter the artwork. Do not add people, animals, text, logos or watermarks.');form.append('size','1024x1024');form.append('quality','low');form.append('output_format','png');const response=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`},body:form});const data=await response.json();if(!response.ok)return res.status(response.status).json({error:data?.error?.message||'Visualisation failed.'});return res.status(200).json({image:`data:image/png;base64,${data.data?.[0]?.b64_json}`,mode});
    }
    if(!fixedScenes[canonicalScene])return res.status(400).json({error:'Please choose an approved standard scene.'});
    const roles=fixedScenes[canonicalScene].slice(0,count);
    const outfitMap={'Classic Formal':'tailored formalwear appropriate to each person','Royal':'formal royal banquet clothing, eveningwear and tasteful ceremonial accessories','Modern Luxury':'polished contemporary luxury eveningwear and refined accessories','Fantasy':'tasteful fantasy ceremonial clothing appropriate to each age','Traditional':'classic festive winter clothing','Cosy':'warm cosy knitwear and winter layers','Elegant':'refined winter party clothing','Winter Wonderland':'magical winter coats, scarves and tasteful snow-themed accessories','Match Day':'modern football supporter clothing with no visible team logos','Retro':'vintage-inspired football clothing with no visible team logos','Championship':'smart contemporary match-day clothing with sporty accessories','Streetwear':'modern casual streetwear, hoodies and trainers','Resort':'stylish warm-weather resort clothing','Beach Casual':'relaxed beach clothing and sandals','Adventure':'practical holiday adventure clothing','Sunset Luxury':'elevated resort eveningwear','Royal Court':'formal aristocratic court clothing with tasteful ceremonial accessories','Medieval':'historically inspired medieval clothing without weapons','Dark Fantasy':'dramatic but family-appropriate fantasy clothing','Fairytale':'whimsical fairytale clothing','Classic':'polished birthday-party clothing','Fun Party':'colourful contemporary party clothing','Explorer':'practical outdoor explorer clothing','Woodland':'comfortable woodland layers and boots','Alpine':'stylish alpine ski clothing','Luxury Lodge':'refined winter resort clothing','Retro Ski':'vintage-inspired ski clothing'};
    const zoomMap={'Standard':'medium-wide composition showing the people and key scene','Wide':'wide cinematic composition showing the people plus substantial surrounding environment','Full Room':'very wide establishing composition showing the full room, architecture, furniture, floor and ceiling while keeping all people clearly visible'};
    const treatmentMap={'Cinematic':'premium cinematic feature-film composition, natural depth, believable lighting and rich environmental detail','Storybook':'beautiful illustrated storybook composition with layered foreground, middle ground and background','Editorial':'high-end editorial illustration with sophisticated composition, realistic styling and controlled detail','Warm Family':'warm inviting family portrait atmosphere with natural expressions and polished environmental detail','Grand':'luxurious dramatic composition with strong architectural detail and elegant lighting'};
    const settingText=setting!=='Default'?`Setting/look: ${setting}. ${outfitMap[setting]||setting}.`:'';
    const clothingText=clothing&&clothing!=='Keep current'?`Character clothing layer: ${clothing}. Change clothing only; preserve every person's identity.`:'';
    const accessoryText=accessories&&accessories!=='None'?`Accessory layer: ${accessories}. Add only tasteful age-appropriate accessories; preserve faces and identity.`:'';
    const avatarText=avatarImage?' A generated customer avatar sheet is also supplied. Treat it as a canonical identity reference for the people; do not merge identities.':'';
    const prompt=`${mode==='final'?'Create the final high-quality personalised artwork suitable for professional printing.':'Create a polished visual preview suitable for customer approval.'} Visual style layer: ${styles[style]||style}. Scene treatment layer: ${treatmentMap[sceneTreatment]||sceneTreatment}. Standard scene: ${canonicalScene}. EXACTLY ${count} PEOPLE. Fixed roles: ${roles.map((r,i)=>`slot ${i+1}: ${r}`).join('; ')}. ${zoomMap[zoom]||zoomMap.Wide}. Keep the approved scene architecture and camera composition consistent between customers. Build a believable, professionally illustrated environment with strong foreground, middle-ground and background detail; avoid generic empty backgrounds, icons, collages or cramped close-ups. ${settingText} ${clothingText} ${accessoryText}${avatarText} Treat ALL original photos as identity references, not composition. Discard their seating, poses, camera position, body orientation, spacing and cropping. Preserve each supplied person's facial characteristics, hair, approximate age, skin tone, body proportions, glasses and distinctive features. Never invent an extra person or remove one. Never add an animal unless the customer instruction explicitly requests a real pet from the source photos. ${adjustments?`Customer instruction: ${adjustments}`:''} No text, logos or watermarks.`;
    const form=new FormData();sourceImages.forEach((src,i)=>{const a=parseImage(src);form.append('image[]',new Blob([a.buffer],{type:a.mime}),`source-${i+1}.jpg`);});if(avatarImage){const av=parseImage(avatarImage);form.append('image[]',new Blob([av.buffer],{type:av.mime}),'avatars.png');}form.append('model','gpt-image-2');form.append('prompt',prompt);form.append('size','1024x1024');form.append('quality',mode==='final'?'high':'low');form.append('output_format','png');const response=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`},body:form});const data=await response.json();if(!response.ok)return res.status(response.status).json({error:data?.error?.message||'Image generation failed.'});const result=data?.data?.[0];if(!result?.b64_json)return res.status(502).json({error:'The image service returned no image.'});return res.status(200).json({image:`data:image/png;base64,${result.b64_json}`,mode,people:count,scene:canonicalScene});
  }catch(error){console.error('Generation error:',error);return res.status(500).json({error:error.message||'Something went wrong while creating the image.'});}
}
