import fs from 'fs';
export default async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
 const key=process.env.OPENAI_API_KEY;if(!key)return res.status(500).json({error:'OPENAI_API_KEY is not configured on the server.'});
 try{
  const b=req.body||{}, {image,images=[],avatarImage,roomImage,style,scene,setting='Default',clothing='Keep current',accessories='None',sceneTreatment='Cinematic',zoom='Wide',mode='preview',personCount,adjustments=''}=b;
  const sources=Array.isArray(images)&&images.length?images.filter(Boolean).slice(0,5):(image?[image]:[]);
  const styles={'Anime':'cinematic Japanese anime illustration, polished feature-film quality, expressive faces, detailed hair and eyes, sophisticated cel shading','Fairytale Animation':'premium modern fairytale animated-film illustration, richly detailed painterly characters, expressive faces, soft cinematic lighting','3D Cartoon':'high-end 3D animated feature-film character render, realistic materials, detailed hair and clothing, expressive natural faces, cinematic lighting','Comic Book':'premium graphic-novel illustration, believable anatomy, detailed ink linework, controlled comic shading, rich painted colour','Chibi':'premium chibi character illustration, cute proportions, large expressive eyes, detailed hair and clothing, polished digital painting','Watercolour':'high-end editorial watercolour portrait, recognisable realistic features, delicate layered washes, paper texture, fine brush detail','Pencil Illustration':'highly detailed graphite pencil illustration, realistic facial structure, individual hair strokes, fine shading and paper texture','Pop Art':'premium contemporary pop-art portrait, recognisable face and anatomy, bold graphic colour blocking, crisp halftone texture'};
  const scenes={
   'Grand Banquet':'an elegant heritage dining hall with tall windows, warm chandeliers, a long dressed banquet table, layered floral centrepieces, polished timber and deep architectural perspective; sophisticated family celebration, not a generic restaurant',
   'Christmas Morning':'a beautifully decorated family living room at Christmas, substantial tree, wrapped presents, fireplace, stockings, soft morning light, tasteful furniture and layered seasonal details; cosy but premium',
   'Football Stadium':'a believable modern football stadium interior with sweeping stands, pitch-side tunnel, floodlights, seating tiers, advertising boards without logos and strong architectural depth; cinematic match-day atmosphere',
   'Tropical Holiday':'a premium Mediterranean/tropical resort shoreline with turquoise water, elegant loungers, parasols, palms, textured sand and distant coastline; bright natural daylight and generous environmental depth',
   'Enchanted Castle':'a grand fairytale castle interior with sweeping staircase, tall arched windows, stone and timber architecture, warm fireplace light, banners and rich layered furnishings; magical but family-friendly',
   'Birthday Party':'a stylish family birthday celebration room with decorated table, layered balloons, cake table, presents, bunting, warm practical lighting and believable furniture; premium party photography composition',
   'Camping Adventure':'a beautiful woodland campsite with detailed tent, picnic table, campfire area, lanterns, trees, distant hills and evening atmosphere; substantial foreground and background depth',
   'Ski Holiday':'a refined alpine ski resort scene with snowy mountain backdrop, timber lodge, ski lift infrastructure, piste, winter trees and warm lodge lighting; expansive cinematic depth'
  };
  const roles={
   'Grand Banquet':['standing at the head of the banquet table','seated on the left side of the table','seated on the right side of the table','seated further along the table','standing beside the table'],
   'Christmas Morning':['kneeling beside the tree with a present','sitting on the floor opening a present','sitting near the presents','standing beside the tree','standing near the fireplace'],
   'Football Stadium':['standing pitch-side','sitting in the front row','standing beside the advertising boards','walking down the stadium steps','standing near the tunnel entrance'],
   'Tropical Holiday':['standing beside the shoreline','sitting on a beach lounger','walking near the water','sitting beneath a parasol','standing near tropical plants'],
   'Enchanted Castle':['standing on the grand staircase','standing beside a window','standing beside a castle table','standing near the fireplace','standing in the hall'],
   'Birthday Party':['standing beside the birthday cake','sitting near the presents','sitting at the party table','standing beside the decorations','standing near the party table'],
   'Camping Adventure':['standing beside the tent','sitting beside the campfire','sitting on a camping chair','walking beside the campsite','standing beside the picnic table'],
   'Ski Holiday':['standing on the snowy slope','sitting at the ski lodge','walking near the lift','standing beside the ski hut','standing beside the piste']
  };
  const aliases={'Banquet':'Grand Banquet','Christmas':'Christmas Morning','Football':'Football Stadium','Beach':'Tropical Holiday','Birthday':'Birthday Party','Ski Resort':'Ski Holiday','Medieval Castle':'Enchanted Castle'}, canonical=aliases[scene]||scene,count=Math.max(1,Math.min(5,Number(personCount)||1));
  const parse=data=>{const [meta,enc]=String(data||'').split(',',2),m=meta.match(/^data:(image\/[\w.+-]+);base64$/);if(!m||!enc)throw Error('Invalid image data.');return{buffer:Buffer.from(enc,'base64'),mime:m[1]}};
  const responseText=d=>typeof d?.output_text==='string'?d.output_text:(d?.output||[]).flatMap(x=>x?.content||[]).filter(x=>typeof x?.text==='string').map(x=>x.text).join('\n');
  if(mode==='styleExamples'){
   const p=process.cwd()+'/assets/style-examples/style-sheet.jpg';if(!fs.existsSync(p))return res.status(500).json({error:'Permanent style example sheet is missing.'});
   return res.status(200).json({image:`data:image/jpeg;base64,${fs.readFileSync(p).toString('base64')}`,mode,fixed:true});
  }
  if(mode==='analyse'){
   if(!sources.length)return res.status(400).json({error:'Please provide at least one photo.'});
   const content=[{type:'input_text',text:'Analyse ALL supplied customer photos together. Identify UNIQUE people across the whole set; the same person in multiple photos counts once. Count pets separately. Do not invent anyone. Return ONLY JSON: {"people":number,"pets":number,"notes":"brief neutral description"}.'},...sources.map(x=>({type:'input_image',image_url:x}))];
   const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.6-luna',input:[{role:'user',content}],max_output_tokens:300})}),d=await r.json();if(!r.ok)return res.status(r.status).json({error:d?.error?.message||'Photo analysis failed.'});
   let j;try{j=JSON.parse(responseText(d).replace(/```json|```/g,'').trim())}catch{j={people:1,pets:0,notes:'Please confirm the detected people count.'}};return res.status(200).json({people:Math.max(1,Math.min(5,Number(j.people)||1)),pets:Math.max(0,Number(j.pets)||0),notes:String(j.notes||'')});
  }
  if(!sources.length||!style)return res.status(400).json({error:'Please provide at least one photo and a style.'});
  const formImages=extra=>{const f=new FormData();sources.forEach((src,i)=>{const a=parse(src);f.append('image[]',new Blob([a.buffer],{type:a.mime}),`source-${i+1}.jpg`)});if(extra){const a=parse(extra);f.append('image[]',new Blob([a.buffer],{type:a.mime}),'avatars.png')}return f};
  if(mode==='avatars'){
   const p=`Create a clean approval sheet of EXACTLY ${count} distinct personalised character avatars from ALL supplied customer photos. Visual style: ${styles[style]||style}. Treat photos as identity references, not composition. Combine unique people across all photos, keep each person separate, preserve face, hair, skin tone, approximate age, body proportions, glasses and distinctive features. Use consistent chest-up or waist-up portraits on a neutral background. ${adjustments?`Customer instruction: ${adjustments}`:''} Do not invent people or animals. No text, logos or watermarks.`;
   const f=formImages();f.append('model','gpt-image-2');f.append('prompt',p);f.append('size','1024x1024');f.append('quality','low');f.append('output_format','png');
   const r=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${key}`},body:f}),d=await r.json();if(!r.ok)return res.status(r.status).json({error:d?.error?.message||'Avatar generation failed.'});return res.status(200).json({image:`data:image/png;base64,${d.data?.[0]?.b64_json||''}`,people:count,mode});
  }
  if(mode==='room'){
   if(!roomImage)return res.status(400).json({error:'Please provide a room image.'});const a=parse(image),room=parse(roomImage),f=new FormData();f.append('model','gpt-image-2');f.append('image[]',new Blob([a.buffer],{type:a.mime}),'artwork.png');f.append('image[]',new Blob([room.buffer],{type:room.mime}),'room.jpg');f.append('prompt','Use the supplied room photo as the exact environment. Place the supplied finished artwork as a framed print on a suitable visible wall. Keep architecture, furniture, lighting and perspective realistic. Do not alter the artwork.');f.append('size','1024x1024');f.append('quality','low');f.append('output_format','png');const r=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${key}`},body:f}),d=await r.json();if(!r.ok)return res.status(r.status).json({error:d?.error?.message||'Visualisation failed.'});return res.status(200).json({image:`data:image/png;base64,${d.data?.[0]?.b64_json||''}`,mode});
  }
  if(!roles[canonical])return res.status(400).json({error:'Please choose an approved standard scene.'});
  const zoomText={Standard:'medium-wide composition showing the people and key scene',Wide:'wide cinematic composition showing the people plus substantial surrounding environment','Full Room':'very wide establishing composition showing the full room, architecture, furniture, floor and ceiling while keeping every person clearly visible'};
  const treatment={Cinematic:'premium cinematic feature-film composition, natural depth and believable lighting',Storybook:'beautiful illustrated storybook composition with layered foreground, middle ground and background',Editorial:'high-end editorial illustration with sophisticated composition and controlled detail','Warm Family':'warm inviting family portrait atmosphere with natural expressions and polished environmental detail',Grand:'luxurious dramatic composition with strong architectural detail and elegant lighting'};
  const prompt=`${mode==='final'?'Create the final high-quality personalised artwork suitable for professional printing.':'Create a polished customer-approval preview.'} Visual style layer: ${styles[style]||style}. Scene treatment layer: ${treatment[sceneTreatment]||sceneTreatment}. STANDARD SCENE BLUEPRINT: ${scenes[canonical]}. EXACTLY ${count} PEOPLE. Fixed character roles: ${roles[canonical].slice(0,count).map((x,i)=>`slot ${i+1}: ${x}`).join('; ')}. Camera: ${zoomText[zoom]||zoomText.Wide}. ${setting!=='Default'?`Setting/look: ${setting}.`:''} Clothing layer: ${clothing}. Accessory layer: ${accessories}. Build a sophisticated, believable environment with deliberate foreground, middle-ground and background structure, realistic scale, clear focal hierarchy, attractive lighting and enough negative space around the characters. Keep the approved scene architecture and camera logic consistent between customers. Avoid generic empty backgrounds, icons, collages, flat studio backdrops or cramped close-ups. Treat every original photo as identity reference only: discard original pose, seating, camera position, spacing, cropping and background. Preserve each person's identity and keep identities separate. Never invent an extra person or remove one. ${adjustments?`Customer instruction: ${adjustments}`:''} No text, logos or watermarks.`;
  const f=formImages(avatarImage);f.append('model','gpt-image-2');f.append('prompt',prompt);f.append('size','1024x1024');f.append('quality',mode==='final'?'high':'low');f.append('output_format','png');const r=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${key}`},body:f}),d=await r.json();if(!r.ok)return res.status(r.status).json({error:d?.error?.message||'Image generation failed.'});return res.status(200).json({image:`data:image/png;base64,${d.data?.[0]?.b64_json||''}`,mode,people:count,scene:canonical});
 }catch(e){console.error(e);return res.status(500).json({error:e.message||'Something went wrong while creating the image.'})}
}